### ISSUE TITLE
No windows binaries for GPT4All

### ISSUE THREAD

**Issue by ParisNeo** [nomic-ai/nomic#124]
Hi everyone,

I was trying to test the GPT4All on My PC, and was faced with the problem that it doesn't have a binary version of windows :

Your platform is not supported: Windows. Current binaries supported are x86 Linux and ARM Macs.

Is there a way, a windows version coming soon?
I think many people around the world use this platform so it would be helpful not to be forced to install WSL to do this.

Best regards

**Comment by vbwyrde** [comment]
I agree with this point.  It would be nice to be able to do work with GPT4All across the board on my Windows machine, as I have my development environment setup to use a lot of tools that relate to Windows dev on that machine and integrating AI with it would be extremely helpful.  I think this is likely true for a lot of people in the community who happen to be Windows-based developers working on the Microsoft stack.

**Comment by ParisNeo** [comment]
That's a verry old issue
HHH. Now I have built an entire multi platform chat tool. You can look here:
https://github.com/nomic-ai/gpt4all-ui

**Comment by vbwyrde** [comment]
Thanks ParisNeo.  That looks awesome enough, for sure.  The reason this came up for me, btw, is because I am teaching myself AI / ML from the ground up and my goal is to be able to run and train my own models on my local machine.  I got GPT4All and am working on a LangChain implementation.  I followed the instructions here: https://github.com/nomic-ai/gpt4all#gpu-interface ... and when I ran the sample program it suggested that I need to do an install of nomic libraries which I did. Once I did that it then reported that the nomic library does not support windows machines, which lead me to this post.  The reason, btw, I wanted to do this is because I am trying to work my way up to getting GPT4All to run on my GPU on conjunction with the use of LangChain.  Anyway, that's how I wound up here.  I have to say your GUI looks awesome.  However, I'm not sure if it will help me on my route to working with GPT4All in context of LangChain development, and GPU usage.  I will, nevertheless poke into it further and see what I can do with it.  Thank you kindly for your reply!

**Comment by ParisNeo** [comment]
The ui has a backend system. I can build a specific backend to Longchain if I have time. You can byuild one yourself if you want too. the idea is that people can build backends and use my ui to interact with
I have a personalities system etc... So it is a really cool thing. I'm integrating training directly into the ui and many things to come like extensions...

**Comment by vbwyrde** [comment]
I absolutely agree it's awesome.  I will try to work out the LangChain backend in the meantime and see if I can get that going, using your code as a base if I can manage it.  The caveats are that I'm on a Windows machine and I'm finding library versioning a bit of a challenge.  I'm quite new to the environment, however, but that said, I've been programming for 25+ years so I'm hoping it won't take me long to get the hang of it.  If I make progress with the LangChaing piece I will be happy to share my findings with you.  Thanks for the work you've done!  It's great.

**Comment by ParisNeo** [comment]
25 years of coding, you should be able tobasically learn any thing. I learned Vue.js overnight and all the new ui is in vue basically built by 2 people. So i don't think you'll find it difficult.
